config/routes.rb
Rails.application.routes.draw do
  root 'welcome#index'
  resources :jobs, only: [:index, :create, :show]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/job.rb
class Job
  attr_reader :uid, :title, :information, :landing_page, :company_name
  @@all ||= []

  def initialize(options = {})
    @uid = options[:uid]
    @title = options[:title]
    @information = options[:information]
    @landing_page = options[:landing_page]
    @company_name = options[:company_name]
    @@all << self unless @@all.find{ |job| job.uid == uid }
  end

  def self.all
    @@all
  end

  def self.find_by(uid: uid)
    self.all.find{ |job| job.uid == uid.to_i }
  end
end

app/models/job_constructor.rb
class JobConstructor

  def perform(page)
    gateway = MuseGateway.new
    results = gateway.fetch("https://api-v2.themuse.com/jobs?page=#{page}")['results']
    build_jobs(results)
  end

  def build_jobs(job_data)
    job_data.each do |job|
      Job.new(job['name'], job['refs']['landing_page'], job['company']['name'])
    end
  end
end

app/models/muse_gateway.rb
require 'httparty'

class MuseGateway
  include HTTParty

  def fetch(url_endpoint)
    response = HTTParty.get(url_endpoint)
    case response.code
    when 200..299
      response
    else
      raise StandardError
    end
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/jobs_controller.rb
class JobsController < ApplicationController
  def create
    gateway = MuseGateway.new
    results = gateway.fetch("https://api-v2.themuse.com/jobs?company=#{params[:company]}&page=1")['results']
    @jobs = results.map do |job|
      Job.new({ uid: job['id'], title: job['name'], information: job['contents'], landing_page: job['refs']['landing_page'], company_name: job['company']['name']})
    end
    render 'jobs/index'
  end

  def index
    redirect_to job_path(params[:uid])
  end

  def show
    @job = Job.find_by(uid: params[:id])
  end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/jobs/index.html.erb
Which job did you apply for?

<% @jobs.each do |job| %>
  <form class="" action="<%=jobs_path%>" method="get">
    <%=job.title%>
    <input type="hidden" name="uid" value="<%=job.uid%>">
    <input type="submit" value="Select">
  </form>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>ThankYou</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/welcome/index.html.erb
<p>
  So you just had a job interview and you want to write a thank you note?
</p>
<p>
  Let us help you!<br>
<%= form_tag("/jobs", method: "post") do %>
  First, tell us what company you interviewed with.<br>
  Company name:
  <input type="text" name="company">
  <input type="submit" value="Submit">
<% end %>
</p>